### ISSUE TITLE
Refactor: Quests

### ISSUE THREAD

**Issue by HaedHutner** [Atherys-Horizons/AtherysQuests#41]
Currently there is some logic contained within the Quest implementation classes. This includes SimpleQuest and StagedQuest. This should be moved into a service and the classes should be reduced to containing only getters/setters.

**Comment by fingoltin** [comment]
Additionally, quests need a way to support some form of modifiers. Examples are `Timed`, `Deliverable`, `Repeatable`, etc. They modify how the quest can be completed, but not how the quest actually functions.
