### ISSUE TITLE
Repeatable quests

### ISSUE THREAD

**Issue by raxiam** [Atherys-Horizons/AtherysQuests#53]
**Problem:**
Currently quests can only be completed once. In order to maximise playability, quests should be made repeatable.
**Proposed Solution:**
`Quest makeQuestRepeatable(Quest q, Integer minutes, Integer limit)`

`Integer minutes` is the interval for when a quest can be repeated. Once a player has completed or failed a quest (due to timed quests), the interval starts its counter and locks the player from picking up the quest until it's done counting.

If `Integer limit` is passed a `0` or `null` (whichever is easiest) the quest can be repeated an unlimited amount of times. Otherwise, the number passed (if `limit`>1) is the exact amount of times it can be repeated.

**Comment by HaedHutner** [comment]
To make this a bit easier to use, maybe use a Period object of some sort, like the that comes with the Java 8s datetime api

**Comment by fingoltin** [comment]
> To make this a bit easier to use, maybe use a Period object of some sort, like the that comes with the Java 8s datetime api

I think the `Duration` class will work pretty well.
