### ISSUE TITLE
hasReachedStageOfRequirment

### ISSUE THREAD

**Issue by raxiam** [Atherys-Horizons/AtherysQuests#57]
**Problem:**
Currently, a small amount of requirements are available. Although the ones currently available are useful, more requirements would simplify the design process and better the possibilities in this regard.

**Proposed Solution:**
`Requirement hasReachedStageOfRequirement(Quest q, Int index)`
`index` corresponds to the index number in the `stageOf` list. Once the defined index is reached, the requirement is met.

**Use case:**
Main use case would be to simplify dialogue hiding during quests which has lots of dialogue, however, not its only. It could potentially be used for questlines and branching as well.

**Comment by fingoltin** [comment]
Implemented; just needs testing.
